### PR TITLE
Formatted source code under the LLVM format (#29)

### PR DESCRIPTION
**Pull request by felix642**
Formatted source code under the LLVM format and removed some C++ only headers. 

The full standard can be found here: https://llvm.org/docs/CodingStandards.html

Applying the same format on every file gives us a baseline on what type of format to use when contributing to the project. 
Consistently using the same style across the whole code base makes it easier to read which makes it also easier to write for potential collaborators. 

To format the source code we used a .clang-format file that we did not commit to this repository to keep the project as simple as possible.  If anyone is interested to see it feel free to ask me. 

@nicholaslegrand102

### CODE REVIEW

**Comment by lmusa** [comment]
GFM

**Comment by hardik-dalal** [comment]
@felix642 looks good to me. If it's okay, I suggest attaching `.clang-format` file to this PR for book keeping purposes.

**Comment by felix642** [comment]
Hi @hardik-dalal,

This is a great idea! I don't know why I didn't think of that.
Here's the file that we used to format the source code : [clang-format.zip](https://github.com/1chipML/1chipML/files/10524200/clang-format.zip)

I had to zip the file to upload it on GitHub. If you unzip it there should be a .clang-format file inside with the config that we used.

**Comment by lmusa** [comment]
Would you plan to put the zip file into git?

**Comment by felix642** [comment]
Hi @lmusa, 

I do not think adding a .zip file to the official repository is a good idea. The  .clang-format file is used with the clang-format executable to automatically format source code following a strict standard. 

Most of us will be using it to keep a standardized format throughout the project, but we did not add it to the git repository since we felt like this would impose too much of a strict standard on new collaborators. 

I think that in the long run, this would be beneficial but for now, let's just format the current files and wait a bit before adding some constraints on new code. 

What do you think?

**Comment by lmusa** [comment]
I agree with your answer. 
Approve to merge.

**Pull request merged**
